secret: "" # if set, this secret will be required for clients to connect
cygwin-path: C:\cygwin64 # if running on windows, set this to the directory cygwin w/ minimodem is installed
dialers:
  default:
    client: gvoice # name/id of the connected client
    client-number-format: phone # can be either phone or a regexp. if a regexp with a capturing group is provided, the number is rewritten to the capturing group's value
    client-number-region: US # if format is phone, this sets the default country for numbers without country codes
    map: # a map of numbers to [client, number]
      '#': [dialer, predefined]
    dial-tone: [350, 440] # dial tone frequencies
  predefined:
    map:
      123: [discord, 86262214066970624]
      456: [gvoice, 13034997111]
    dial-tone: [400]

devices:
  # devices are keyed by their serial number - default is used if the serial number doesn't exist
  default:
    dialer: default
    caller-id: after-first-ring # before-first-ring, after-first-ring
    ring-list-type: whitelist # whitelist, blacklist
    ring-list:
      - discord # allow all calls from discord
      - [gvoice, 13034997111] # only ring from a specific number
      